# Usage of Numpy

In [3]:
import numpy as np

## 1. Creating arrays

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [8]:
print("1D Array:", arr1)
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## 2. Array operations

In [11]:
print("Addition:", arr1 + 5)  # add 5 to each element
print("Multiplication: ", arr1 * 2)  # multiply each element by 2
print("Square root:", np.sqrt(arr1))

Addition: [ 6  7  8  9 10]
Multiplication:  [ 2  4  6  8 10]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


## 3. Array statistics

In [14]:
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))
print("Min:", np.min(arr1))

Sum: 15
Mean: 3.0
Max: 5
Min: 1


### 4. Creating special arrays

In [17]:
zeros = np.zeros((2, 3))  # 2x3 matrix of zeros
ones = np.ones((3, 3))   # 3x3 matrix of ones

In [19]:
print("Zeros:\n", zeros)
print("Ones:\n"), ones

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:



(None,
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))